import _Loading from "./loading";
import _Progress from "./progress";
import _Opinion from "./opinion";
import _TitleComp from "./title";
import _Description from "./description";
export const Loading = _Loading;
export const Progress = _Progress;
export const Opinion = _Opinion;
export const TitleComponent = _TitleComp;
export const Description = _Description;
